// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dazmyjjanixtjiyiixqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhem15amphbml4dGppeWlpeHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjI0NzAsImV4cCI6MjA2Mjc5ODQ3MH0.0ET70vWucSDbTsPai3fWZQiYDc625SzWxFySNKIZnZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);